### ISSUE TITLE
2022.12.16.5 - Plugin does not show up

### ISSUE THREAD

**Issue by Beet4** [N6REJ/AdiBags_Bears_Keystones#3]
After the recent update to 2022.12.16.5 the plugin no longer show up in Adibags. AddOn is enabled but using 0 KiB memory.

**Comment by N6REJ** [comment]
please check 2022.12.17 when it updates.

**Comment by Frurox** [comment]
I was just going to bring the same issue. I downloaded the zip from the code and it looks good now.
<img width="53" alt="image" src="https://user-images.githubusercontent.com/47403751/208569515-30cd074b-0b90-4b1a-a786-7903b43730f0.png">
Thanks again! Will also wait for Curse to update latest version.

**Comment by N6REJ** [comment]
Thanks for letting me know.  PTR has been down every time I go to test so the only way has been live testing.  There was a heck of a lot that needed to change in DF and its been complicated.  
I am still not done doing ALL the professions but I'm working on it.  Continue to report any status changes, bugs, fixes, etc PLEASE.

**Comment by Frurox** [comment]
Thank you for the hard work on this. FYI 2022.12.17 still not live in CurseForge

**Comment by N6REJ** [comment]
ok, I pushed it again.  It will show up as 2022.12.21 and I can see its there just waiting for approval.

**Comment by Beet4** [comment]
2022.12.21 came up on CurseForge fine and that version works fine. :) Thank you!
